#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Polyline;
                ref class Line;
                ref class Ellipse;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ComboBox;
                ref class Viewbox;
                ref class Button;
                ref class TextBlock;
                ref class RichEditBox;
            }
        }
    }
}

namespace line_characteristics_calculator
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Shapes::Polyline^ data_graph;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ a_begin_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ a_begin_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ a_end_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ a_end_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ b_begin_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ b_begin_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ b_end_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ b_end_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ c_begin_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ c_begin_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ c_end_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ c_end_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ d_begin_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ d_begin_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ d_end_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ d_end_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ e_begin_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ e_begin_mark;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ e_end_combo;
        private: ::Windows::UI::Xaml::Controls::Viewbox^ e_end_mark;
        private: ::Windows::UI::Xaml::Controls::Button^ calc_btn;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ method_combo;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ step_ans_lbl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ angle_ans_lbl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ crosspoint_ans_lbl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ellipse_center_ans_lbl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ellipse_cemiaxes_ans_lbl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ellipse_decline_ans_lbl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ellipse_excentricity_ans_lbl;
        private: ::Windows::UI::Xaml::Controls::Button^ read_file_btn;
        private: ::Windows::UI::Xaml::Controls::RichEditBox^ observations_notes_edtor;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ info_lbl;
        private: ::Windows::UI::Xaml::Shapes::Line^ a_line;
        private: ::Windows::UI::Xaml::Shapes::Line^ b_line;
        private: ::Windows::UI::Xaml::Shapes::Line^ c_line;
        private: ::Windows::UI::Xaml::Shapes::Line^ d_line;
        private: ::Windows::UI::Xaml::Shapes::Polyline^ e_line;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ approximated_curv_line;
        private: ::Windows::UI::Xaml::Shapes::Polyline^ approximated_curv_line_2;
    };
}

