//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::line_characteristics_calculator::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::line_characteristics_calculator::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->data_graph = safe_cast<::Windows::UI::Xaml::Shapes::Polyline^>(__target);
        }
        break;
    case 3:
        {
            this->a_begin_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->a_begin_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_a_begin_callback);
        }
        break;
    case 4:
        {
            this->a_begin_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 5:
        {
            this->a_end_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->a_end_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_a_end_callback);
        }
        break;
    case 6:
        {
            this->a_end_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 7:
        {
            this->b_begin_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->b_begin_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_b_begin_callback);
        }
        break;
    case 8:
        {
            this->b_begin_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 9:
        {
            this->b_end_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->b_end_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_b_end_callback);
        }
        break;
    case 10:
        {
            this->b_end_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 11:
        {
            this->c_begin_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->c_begin_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_c_begin_callback);
        }
        break;
    case 12:
        {
            this->c_begin_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 13:
        {
            this->c_end_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->c_end_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_c_end_callback);
        }
        break;
    case 14:
        {
            this->c_end_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 15:
        {
            this->d_begin_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->d_begin_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_d_begin_callback);
        }
        break;
    case 16:
        {
            this->d_begin_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 17:
        {
            this->d_end_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->d_end_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_d_end_callback);
        }
        break;
    case 18:
        {
            this->d_end_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 19:
        {
            this->e_begin_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->e_begin_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_e_begin_callback);
        }
        break;
    case 20:
        {
            this->e_begin_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 21:
        {
            this->e_end_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->e_end_combo))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::select_e_end_callback);
        }
        break;
    case 22:
        {
            this->e_end_mark = safe_cast<::Windows::UI::Xaml::Controls::Viewbox^>(__target);
        }
        break;
    case 23:
        {
            this->calc_btn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->calc_btn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::calc_btn_click_callback);
        }
        break;
    case 24:
        {
            this->method_combo = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
        }
        break;
    case 25:
        {
            this->step_ans_lbl = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 26:
        {
            this->angle_ans_lbl = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 27:
        {
            this->crosspoint_ans_lbl = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 28:
        {
            this->ellipse_center_ans_lbl = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 29:
        {
            this->ellipse_cemiaxes_ans_lbl = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 30:
        {
            this->ellipse_decline_ans_lbl = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 31:
        {
            this->ellipse_excentricity_ans_lbl = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 32:
        {
            this->read_file_btn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->read_file_btn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::line_characteristics_calculator::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::on_read_file_btn_click);
        }
        break;
    case 33:
        {
            this->observations_notes_edtor = safe_cast<::Windows::UI::Xaml::Controls::RichEditBox^>(__target);
        }
        break;
    case 34:
        {
            this->info_lbl = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 35:
        {
            this->a_line = safe_cast<::Windows::UI::Xaml::Shapes::Line^>(__target);
        }
        break;
    case 36:
        {
            this->b_line = safe_cast<::Windows::UI::Xaml::Shapes::Line^>(__target);
        }
        break;
    case 37:
        {
            this->c_line = safe_cast<::Windows::UI::Xaml::Shapes::Line^>(__target);
        }
        break;
    case 38:
        {
            this->d_line = safe_cast<::Windows::UI::Xaml::Shapes::Line^>(__target);
        }
        break;
    case 39:
        {
            this->e_line = safe_cast<::Windows::UI::Xaml::Shapes::Polyline^>(__target);
        }
        break;
    case 40:
        {
            this->approximated_curv_line = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(__target);
        }
        break;
    case 41:
        {
            this->approximated_curv_line_2 = safe_cast<::Windows::UI::Xaml::Shapes::Polyline^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::line_characteristics_calculator::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


